#!/bin/bash

if [ ${VIRTUAL_ENV:+x} ]
    then echo "VIRTUAL_ENV is already specified"
    else export VIRTUAL_ENV=.tox/venv
fi

echo "VIRTUAL_ENV = $VIRTUAL_ENV"
echo "-i|--integration for run only integration tests"
echo "-a|--all for run all tests"
echo "-h|--hadoop for run only hadoop tests"
echo "-l|--load for run only load hadoop tests"
echo "Running tests"
echo "============="
com='0'

while [ $# -gt 0 ]; do
  case "$1" in
    -i|--integration) com='0';;
    -h|--hadoop) com='1';;
    -l|--load) com='2';;
    -a|--all) com='3';;
  esac
  shift
done


export NOSE_WITH_OPENSTACK=1
export NOSE_OPENSTACK_COLOR=1
export NOSE_OPENSTACK_RED=1.5
export NOSE_OPENSTACK_YELLOW=1.000
export NOSE_OPENSTACK_SHOW_ELAPSED=1
export NOSE_OPENSTACK_STDOUT=1
export NOSE_XUNIT=1

find . -type f -name "*.pyc" -delete

if [ $com == '3' ]; then
    $VIRTUAL_ENV/bin/nosetests ../integration/ -x $@
    elif [ $com == '2' ]; then
    $VIRTUAL_ENV/bin/nosetests ../integration/load_test.py $@
        elif [ $com == '1' ]; then
            $VIRTUAL_ENV/bin/nosetests integration/hadoop_test.py -x $@
            elif [ $com == '0' ]; then
                $VIRTUAL_ENV/bin/nosetests ../integration/ -x -I \
                 "load_test.*" -I "hadoop_test.*"  $@
fi


